name: Build ctrWWG-Plugin

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: pablomk7/libctrpf:0.8.0

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build Plugin
      run: make

    - name: Upload 3GX
      uses: actions/upload-artifact@v4
      with:
        name: ctrWWG-Plugin
        path: |
          ctrWWG-Plugin.3gx
          ctrWWG-Plugin.elf

    - name: Upload on success
      if: success()
      run: echo "Build successful - download the Artifact"
